services:
  - type: web
    name: video-reminder-web
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: BUILD_TARGET
        value: "web"
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
